#!/bin/bash
#
# SPDX-FileCopyrightText: 2015 Jonathan Rajotte <jonathan.rajotte-julien@efficios.com>
# SPDX-FileCopyrightText: 2025 Michael Jeanson <mjeanson@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="UST - Getcpu override plugin"

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../..

TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME"

LTTNG_UST_GETCPU_PLUGIN_SO="$CURDIR/.libs/lttng-ust-getcpu-override-test.so"

NUM_EVENT=256
EVENT_WAIT_USEC=1
EVENT_NAME="tp:tptest"

NUM_TESTS=20

SEQUENCE_SEED=(
100 57 232 236 42 193 224 184 216 150 92 91 108 118 55 243 65 101 209 0 147 36
29 34 49 188 174 105 253 245 227 238 112 20 222 201 102 175 119 19 132 41 78 90
114 64 138 14 48 18 162 85 204 124 133 73 172 106 241 126 28 104 111 21 127 219
9 244 237 189 59 214 52 141 107 26 25 199 3 157 117 234 33 44 46 84 69 155 122
250 231 86 239 76 190 120 1 94 206 8 148 159 167 215 164 31 217 61 71 125 68 109
195 177 95 82 142 182 129 87 37 140 134 186 173 39 116 143 254 229 131 67 121
192 240 15 221 30 242 185 80 170 135 51 187 194 246 12 225 181 137 211 228 88
218 27 233 161 77 252 123 93 220 248 205 223 144 128 196 70 247 210 178 203 154
24 169 149 163 35 7 151 103 197 139 165 158 207 72 113 145 45 183 11 198 43 81
230 97 96 2 66 213 146 179 22 58 54 38 160 200 235 226 156 56 208 249 32 176 168
110 191 79 152 115 10 74 60 251 17 83 180 171 202 40 166 255 53 212 98 5 50 99 4
89 13 63 6 136 153 23 16 47 130 75 62
)

# shellcheck source-path=SCRIPTDIR/../../..
source "$TESTDIR/utils/utils.sh"

# Equivalent to the syconf(_SC_NPROCESSORS_CONF) call.
num_cpus=$(conf_proc_count)

# MUST set TESTDIR before calling those functions

compare()
{
	local expected_to_fail=$1
	local trace_path=$2
	local array_to_compare=("${@:3}")
	local valid=0

	test ${#array_to_compare[*]} -eq ${#SEQUENCE_SEED[*]}
	ok $? "Sequence seed and cpuid sequence have the same size ${#SEQUENCE_SEED[*]}/${#array_to_compare[*]}"

	for (( i = 0; i < ${#SEQUENCE_SEED[*]}; i++ )); do
		if [ "${array_to_compare[$i]}" -ne "$(( ${SEQUENCE_SEED[$i]} % num_cpus))" ]; then
			valid=1
			break
		fi
	done

	if [[ $expected_to_fail -eq "1" ]]; then
		test $valid -ne "0"
		ok $? "Cpuid extraction and seed sequence comparison fails as expected"
	else
		ok $valid "Cpuid extraction and seed sequence comparison"
		if [[ $valid -ne "0" ]]; then
			diag "Dumping arrays after failed comparison"
			for (( i = 0; i < ${#SEQUENCE_SEED[*]}; i++ )); do
				echo -n "# array value is "
				echo -n "${array_to_compare[$i]}"
				echo -n " expected "
				echo "$(( ${SEQUENCE_SEED[$i]} % num_cpus))"
			done
			diag "Dumping trace"
			_run_babeltrace_cmd "$trace_path" | awk '{print "# " $0}'
		fi
	fi
}

compare_ok()
{
	compare 0 "$@"
}

compare_fail()
{
	compare 1 "$@"
}

test_getcpu_override_fail()
{
	local session_name="getcpu-plugin-disabled"
	local trace_path
	local file_testapp_output
	local cpuid_events=()
	local num_events

	diag "Getcpu plugin - no preloaded plugin"

	trace_path=$(mktemp -d -t "tmp.${FUNCNAME[0]}_trace_path.XXXXXX")
	file_testapp_output=$(mktemp -u -t "tmp.${FUNCNAME[0]}_testapp_output.XXXXXX")

	create_lttng_session_ok $session_name "$trace_path"
	enable_ust_lttng_event_ok $session_name "$EVENT_NAME"
	start_lttng_tracing_ok $session_name

	diag "Launching app without getcpu plugin"
	run_testapp_ok "$file_testapp_output" "$TESTAPP_BIN" -i $NUM_EVENT -w $EVENT_WAIT_USEC

	stop_lttng_tracing_ok $session_name
	destroy_lttng_session_ok $session_name

	# Get the cpu_id from each event in an array
	mapfile -t cpuid_events < <(_run_babeltrace_cmd "$trace_path" | sed -n 's/.*cpu_id = \([0-9]*\).*/\1/p')

	num_events=${#cpuid_events[*]}
	test "$num_events" -eq $NUM_EVENT
	ok $? "Extraction without getcpu plugin have $num_events/$NUM_EVENT"
	compare_fail "$trace_path" "${cpuid_events[@]}"

	rm -rf "$trace_path"
	rm -f "$file_testapp_output"
}

test_getcpu_override()
{
	local session_name="getcpu-plugin-enabled"
	local trace_path
	local file_testapp_output
	local cpuid_events=()
	local num_events

	diag "Getcpu plugin - with plugin preloaded"

	trace_path=$(mktemp -d -t "tmp.${FUNCNAME[0]}_trace_path.XXXXXX")
	file_testapp_output=$(mktemp -u -t "tmp.${FUNCNAME[0]}_testapp_output.XXXXXX")

	create_lttng_session_ok $session_name "$trace_path"
	enable_ust_lttng_event_ok $session_name "$EVENT_NAME"
	start_lttng_tracing_ok $session_name

	diag "Launching app with getcpu plugin"
	LTTNG_UST_GETCPU_PLUGIN="$LTTNG_UST_GETCPU_PLUGIN_SO" \
		run_testapp_ok "$file_testapp_output" "$TESTAPP_BIN" -i $NUM_EVENT -w $EVENT_WAIT_USEC

	stop_lttng_tracing_ok $session_name
	destroy_lttng_session_ok $session_name

	# Get the cpu_id from each event in an array
	mapfile -t cpuid_events < <(_run_babeltrace_cmd "$trace_path" | sed -n 's/.*cpu_id = \([0-9]*\).*/\1/p')

	num_events=${#cpuid_events[*]}
	test "$num_events" -eq $NUM_EVENT
	ok $? "Extraction with getcpu plugin have $num_events/$NUM_EVENT"

	compare_ok "$trace_path" "${cpuid_events[@]}"

	rm -rf "$trace_path"
	rm -f "$file_testapp_output"
}

plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

bail_out_if_no_babeltrace

if [ ! -x "$CURDIR/.libs/lttng-ust-getcpu-override-test.so" ]; then
	skip 0 "No shared object generated. Skipping all tests." $NUM_TESTS && exit 0
fi

if [ "$num_cpus" -eq "1" ]; then
	# Skip the test since we cannot perform it as designed since N mod 1
	# is always equals to zero. There is no point testing this on a system
	# with a single configured core. LTTng-UST limits the get_cpu function
	# to return value inside the [0, NUM_CPU - 1] range for a valid event
	# (present in trace).
	skip 0 "Test system only have a single thread. Skipping all tests." $NUM_TESTS && exit 0
fi

start_lttng_sessiond

test_getcpu_override_fail
test_getcpu_override

stop_lttng_sessiond
