#!/bin/bash
#
# SPDX-FileCopyrightText: 2013 Jérémie Galarneau <jeremie.galarneau@efficios.com>
#
# SPDX-License-Identifier: GPL-2.0-only

CURDIR=$(dirname $0)
TESTDIR=${CURDIR}/../../..

source $TESTDIR/utils/utils.sh

start_lttng_sessiond_notap

python3 ${CURDIR}/test_exit-fast.py

stop_lttng_sessiond_notap
