#!/bin/bash
#
# SPDX-FileCopyrightText: 2013 Christian Babeux <christian.babeux@efficios.com>
# SPDX-FileCopyrightText: 2014 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# SPDX-License-Identifier: GPL-2.0-only

TEST_DESC="UST tracer - tracef events"

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../..

TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-tracef"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME"
NR_ITER=100

NUM_TESTS=9

# shellcheck source-path=SCRIPTDIR/../..
source "$TESTDIR/utils/utils.sh"

if [ ! -x "$TESTAPP_BIN" ]; then
	BAIL_OUT "No UST nevents binary detected."
fi

function test_event_tracef()
{
	local session_name="tracef"
	local event_name="lttng_ust_tracef:event"
	local trace_path
	local file_testapp_output

	trace_path=$(mktemp -d -t tmp.test_event_tracef_trace_path.XXXXXX)
	file_testapp_output=$(mktemp -u -t "tmp.${FUNCNAME[0]}_testapp_output.XXXXXX")

	create_lttng_session_ok $session_name "$trace_path"
	enable_ust_lttng_event_ok $session_name $event_name
	start_lttng_tracing_ok $session_name

	run_testapp_ok "$file_testapp_output" "$TESTAPP_BIN" "$NR_ITER" "$NR_USEC_WAIT"

	stop_lttng_tracing_ok $session_name
	destroy_lttng_session_ok $session_name

	trace_match_only $event_name $NR_ITER "$trace_path"

	rm -rf "$trace_path"
	rm -f "$file_testapp_output"
}

# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

bail_out_if_no_babeltrace

start_lttng_sessiond

test_event_tracef

stop_lttng_sessiond
