#!/bin/bash
#
# Copyright (C) - 2013 Christian Babeux <christian.babeux@efficios.com>
# Copyright (C) - 2014 Julien Desfossez <jdesfossez@efficios.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License, version 2 only, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

TEST_DESC="UST tracer - Perf counters"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../..
LTTNG_BIN="lttng"
SESSION_NAME="perf_counters"
EVENT_NAME="tp:tptest"
NUM_TESTS=24
NR_ITER=1
NR_USEC_WAIT=1
TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME/$TESTAPP_NAME"

source $TESTDIR/utils/utils.sh

function enable_ust_lttng_event_per_chan()
{
	sess_name="$1"
	event_name="$2"
	chan_name="$3"

	$TESTDIR/../src/bin/lttng/$LTTNG_BIN enable-event "$event_name" -s $sess_name -c $chan_name -u >/dev/null 2>&1
	ok $? "Enable event $event_name for session $sess_name in channel $chan_name"
}

# Only test parsing of the enabling by raw ID
function test_parsing_raw()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="ust_event_basic"
	CHAN_NAME="mychan"

	create_lttng_session_ok $SESSION_NAME $TRACE_PATH

	enable_ust_lttng_channel_ok $SESSION_NAME $CHAN_NAME

	enable_ust_lttng_event_per_chan $SESSION_NAME $EVENT_NAME $CHAN_NAME

	add_context_ust_ok $SESSION_NAME $CHAN_NAME "perf:thread:raw:r0110:test"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw:rZZZ:test"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw:b0110:test"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw:r0110:"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw:r0110::"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw:r:test"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw:r::"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw::"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw"
	add_context_ust_fail $SESSION_NAME $CHAN_NAME "perf:thread:raw:r0110:test:wrong"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf $TRACE_PATH
}

function test_event_basic()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="ust_event_basic"
	CHAN_NAME="mychan"

	create_lttng_session_ok $SESSION_NAME $TRACE_PATH

	enable_ust_lttng_channel_ok $SESSION_NAME $CHAN_NAME

	enable_ust_lttng_event_per_chan $SESSION_NAME $EVENT_NAME $CHAN_NAME

	add_context_ust_ok $SESSION_NAME $CHAN_NAME "perf:thread:page-fault"

	start_lttng_tracing_ok

	$TESTAPP_BIN $NR_ITER $NR_USEC_WAIT >/dev/null 2>&1

	stop_lttng_tracing_ok

	destroy_lttng_session_ok $SESSION_NAME

	validate_trace "perf_thread_page_fault" $TRACE_PATH
	rm -rf $TRACE_PATH
}

# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

if [ "$(id -u)" == "0" ]; then
        isroot=1
else
        isroot=0
fi

start_lttng_sessiond

test_parsing_raw

skip $isroot "Root access is needed. Skipping UST perf tests." 8 ||
{
	test_event_basic
}

stop_lttng_sessiond
