#!/bin/bash
#
# Copyright (C) - 2014 Geneviève Bastien <gbastien@versatic.net>
# Copyright (C) - 2016 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

TEST_DESC="UST tracer - Test tracepoints using ctf type declarations"

CURDIR=$(dirname $0)
TESTDIR=${CURDIR}/../../..

source $TESTDIR/utils/utils.sh

start_lttng_sessiond_notap

python3 ${CURDIR}/test_type_declarations.py

stop_lttng_sessiond_notap
