#!/bin/bash
#
# SPDX-FileCopyrightText: 2014 Geneviève Bastien <gbastien@versatic.net>
# SPDX-FileCopyrightText: 2016 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="UST tracer - Test tracepoints using ctf type declarations"

CURDIR=$(dirname $0)
TESTDIR=${CURDIR}/../../..

source $TESTDIR/utils/utils.sh

tap_disable
start_lttng_sessiond_notap

python3 ${CURDIR}/test_type_declarations.py

stop_lttng_sessiond_notap
