#!/bin/bash
#
# SPDX-FileCopyrightText: 2012 David Goulet <dgoulet@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="Streaming - Kernel tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../..
EVENT_NAME="sched_switch"
SESSION_NAME=""

TRACE_PATH=$(mktemp -d -t tmp.test_streaming_kernel_trace_path.XXXXXX)

NUM_TESTS=13

source $TESTDIR/utils/utils.sh

function test_kernel_before_start ()
{
	diag "Test kernel streaming with event enable BEFORE start"
	create_lttng_session_uri $SESSION_NAME net://localhost
	lttng_enable_kernel_event $SESSION_NAME $EVENT_NAME
	start_lttng_tracing_ok $SESSION_NAME
	# Give a second
	sleep 1
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME
}

# Deactivated since this feature is not yet available where we can enable
# an event AFTERE tracing has started.
function test_kernel_after_start ()
{
	diag "Test kernel streaming with event enable AFTER start"
	create_lttng_session_uri $SESSION_NAME net://localhost
	start_lttng_tracing_ok $SESSION_NAME
	lttng_enable_kernel_event $SESSION_NAME $EVENT_NAME
	# Give a second
	sleep 1
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME
}

plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

check_skip_kernel_test "$NUM_TESTS" "Skipping all tests." ||
{
	lttng_modules_loaded_fail
	validate_lttng_modules_present

	start_lttng_relayd "-o $TRACE_PATH"
	start_lttng_sessiond

	tests=( test_kernel_before_start )

	for fct_test in ${tests[@]};
	do
		SESSION_NAME=$(randstring 16 0)
		${fct_test}

		# Validate test
		validate_trace_path_kernel_network "$TRACE_PATH" "$SESSION_NAME"
		validate_trace $EVENT_NAME $TRACE_PATH/$HOSTNAME/$SESSION_NAME*
		if [ $? -eq 0 ]; then
			# Only delete if successful
			rm -rf $TRACE_PATH
		else
			break
		fi
	done

	stop_lttng_sessiond
	stop_lttng_relayd
	lttng_modules_loaded_fail
}
