#!/bin/bash
#
# Copyright (c) - 2012 David Goulet <dgoulet@efficios.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by as published by
# the Free Software Foundation; only version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

DIR=`dirname $(readlink -f $0)`

LTTNG_CONSUMER_DEBUG_VALGRIND=1 $DIR/../src/bin/lttng-sessiond/lttng-sessiond --consumerd64-path="$DIR/../src/bin/lttng-consumerd/lttng-consumerd" --consumerd32-path="$DIR/../src/bin/lttng-consumerd/lttng-consumerd" $1
