#!/bin/sh
#
# Copyright (C) - 2013 Jérémie Galarneau <jeremie.galarneau@efficios.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License, version 2 only, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Check for a running sessiond
`pidof lt-lttng-sessiond`
STOP_SESSIOND=$?

CURDIR=$(dirname $0)
TESTDIR=${CURDIR}/../../..

# Try to launch a sessiond before invoking the python test script
if [ $STOP_SESSIOND -ne 0 ]; then
	DIR=$(readlink -f ${TESTDIR})
	${DIR}/../src/bin/lttng-sessiond/lttng-sessiond --daemonize --quiet --consumerd32-path="$DIR/../src/bin/lttng-consumerd/lttng-consumerd" --consumerd64-path="$DIR/../src/bin/lttng-consumerd/lttng-consumerd"
fi

python3 ${CURDIR}/test_baddr-statedump.py

if [ $STOP_SESSIOND -ne 0 ]; then
    kill `pidof lt-lttng-sessiond`
fi
