#!/bin/bash
#
# SPDX-FileCopyrightText: 2017 Jonathan Rajotte-Julien <jonathan.rajotte-julien@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../../

TESTAPP_STATE_PATH=$(mktemp -u -t "tmp.test_notif_kernel_syscall_application_state.XXXXXX")

NUM_TESTS=25

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"
EVENT_GENERATOR_SCRIPT="${CURDIR}/util_event_generator.py"

function test_kernel_syscall_notification
{
	READY_FILE="$(mktemp -u -t "generator_ready.XXXXXX")"
	"${EVENT_GENERATOR_SCRIPT}" --ready-file "${READY_FILE}" --state-file "${TESTAPP_STATE_PATH}" \
				    --iterations 10 --run-once kernel_generate_syscalls \
				    /proc/cpuinfo /proc/cmdline &
	APP_PID=$!
	while [ ! -f "${READY_FILE}" ]; do
		sleep 0.1
	done
	rm -f "${READY_FILE}"

	# Pass the syscall_generator_file for filtering
	"$CURDIR/notification" 5 LTTNG_DOMAIN_KERNEL $APP_PID \
		"$TESTAPP_STATE_PATH"


	kill -SIGUSR2 $APP_PID
	wait $APP_PID 2> /dev/null
}

check_skip_kernel_test &&
{
	plan_skip_all "Skipping all tests."
	exit 0
}

validate_lttng_modules_present
tap_disable

start_lttng_sessiond_notap

test_kernel_syscall_notification

stop_lttng_sessiond_notap

rm -f "$TESTAPP_STATE_PATH"
