#!/bin/bash
#
# SPDX-FileCopyrightText: 2017 Jonathan Rajotte-Julien <jonathan.rajotte-julien@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../../

TESTAPP_STATE_PATH=$(mktemp -u -t "tmp.test_notif_kernel_uprobe_application_state.XXXXXXXXXX")

NUM_TESTS=13

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"
EVENT_GENERATOR_SCRIPT="${CURDIR}/util_event_generator.py"

TESTAPP_PATH=${TESTAPP_PATH:-"$TESTDIR/utils/testapp"}
USERSPACE_PROBE_ELF_TESTAPP_NAME=${USERSPACE_PROBE_ELF_TESTAPP_NAME:-"userspace-probe-elf-binary"}
USERSPACE_PROBE_ELF_TESTAPP_BIN=${USERSPACE_PROBE_ELF_TESTAPP_BIN:-"$TESTAPP_PATH/$USERSPACE_PROBE_ELF_TESTAPP_NAME/.libs/$USERSPACE_PROBE_ELF_TESTAPP_NAME"}

function test_kernel_userspace_probe_notification
{
	READY_FILE="$(mktemp -u -t "generator_ready.XXXXXX")"
	"${EVENT_GENERATOR_SCRIPT}" --ready-file "${READY_FILE}" --state-file "${TESTAPP_STATE_PATH}" --iterations 10 --run-once userspace_probe_testapp &
	APP_PID=$!
	while [ ! -f "${READY_FILE}" ]; do
		sleep 0.1
	done
	rm -f "${READY_FILE}"

	"$CURDIR/notification" 6 LTTNG_DOMAIN_KERNEL \
		$APP_PID "$TESTAPP_STATE_PATH" \
		"$USERSPACE_PROBE_ELF_TESTAPP_BIN" "test_function"

	kill -SIGUSR2 $APP_PID
	wait $APP_PID 2> /dev/null
}

check_skip_kernel_test &&
{
	plan_skip_all "Skipping all tests."
	exit 0
}

if file /bin/bash | grep -q 'ELF 32-bit' && uname -n | grep -q arm ; then
	plan_skip_all "Unsupported"
	exit 0
fi

validate_lttng_modules_present
tap_disable

start_lttng_sessiond_notap

test_kernel_userspace_probe_notification

stop_lttng_sessiond_notap

rm -f "$TESTAPP_STATE_PATH"
