#!/bin/bash
#
# SPDX-FileCopyrightText: 2017 Jonathan Rajotte-Julien <jonathan.rajotte-julien@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../../


TESTAPP_PATH="$TESTDIR/utils/testapp"

GEN_UST_EVENTS_TESTAPP_NAME="gen-ust-events"
GEN_UST_EVENTS_TESTAPP_BIN="$TESTAPP_PATH/$GEN_UST_EVENTS_TESTAPP_NAME"

TESTAPP_STATE_PATH=$(mktemp -u -t "tmp.test_notif_ust_error_application_state.XXXXXX")

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"
EVENT_GENERATOR_SCRIPT="${CURDIR}/util_event_generator.py"

function test_basic_error_path
{
	READY_FILE="$(mktemp -u -t "generator_ready.XXXXXX")"
	USERSPACE_TESTAPP_BIN="${GEN_UST_EVENTS_TESTAPP_BIN}" "${EVENT_GENERATOR_SCRIPT}" \
			     --ready-file "${READY_FILE}" --state-file "${TESTAPP_STATE_PATH}" \
			     --iterations 5 --wait 5 --run-once \
			     userspace_testapp &
	APP_PID=$!
	while [ ! -f "${READY_FILE}" ]; do
		sleep 0.1
	done
	rm -f "${READY_FILE}"

	"$CURDIR/notification" 1 LTTNG_DOMAIN_UST $APP_PID "$TESTAPP_STATE_PATH"

	kill -SIGUSR2 $APP_PID
	wait $APP_PID 2> /dev/null
}

# Avoid spurious tap messages from the shell runner
tap_disable

start_lttng_sessiond_notap

test_basic_error_path

stop_lttng_sessiond_notap

rm -f $TESTAPP_STATE_PATH
