#!/bin/bash
#
# SPDX-FileCopyrightText: 2017 Jonathan Rajotte-Julien <jonathan.rajotte-julien@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../../

TESTAPP_PATH="$TESTDIR/utils/testapp"

GEN_UST_NEVENTS_TESTAPP_NAME="gen-ust-nevents"
GEN_UST_NEVENTS_TESTAPP_BIN="$TESTAPP_PATH/$GEN_UST_NEVENTS_TESTAPP_NAME/$GEN_UST_NEVENTS_TESTAPP_NAME"

TESTAPP_STATE_PATH=$(mktemp -u -t "tmp.test_notif_event_rule_exclusion_ust_application_state.XXXXXX")

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"
EVENT_GENERATOR_SCRIPT="${CURDIR}/util_event_generator.py"

function test_event_rule_condition_exclusion_notification
{
	READY_FILE="$(mktemp -u -t "generator_ready.XXXXXX")"
	USERSPACE_TESTAPP_BIN="${GEN_UST_NEVENTS_TESTAPP_BIN}" "${EVENT_GENERATOR_SCRIPT}" \
			     --ready-file "${READY_FILE}" --state-file "${TESTAPP_STATE_PATH}" \
			     --iterations 5 --wait 5 --run-once userspace_testapp &
	APP_PID=$!
	while [ ! -f "${READY_FILE}" ]; do
		sleep 0.1
	done
	rm -f "${READY_FILE}"

	"$CURDIR/notification" 3 LTTNG_DOMAIN_UST $APP_PID "$TESTAPP_STATE_PATH"

	kill -SIGUSR2 $APP_PID
	wait $APP_PID 2> /dev/null
}

tap_disable
start_lttng_sessiond_notap

test_event_rule_condition_exclusion_notification

stop_lttng_sessiond_notap

rm -rf "$TESTAPP_STATE_PATH"
