#!/bin/bash
#
# SPDX-FileCopyrightText: 2020 Francis Deslauriers <francis.deslauriers@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../../

TEST_TMPDIR=$(mktemp -d -t tmp.test_notifier_discarded_count.XXXXXX)

# Set TMPDIR for further call to mktemp
export TMPDIR="$TEST_TMPDIR"

TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME"

TESTPOINT_BASE_PATH=$(readlink -f "$TEST_TMPDIR/lttng.t_p_n")
TESTPOINT_PIPE_PATH=$(mktemp -u -t "lttng.t_p_n.XXXXXX")
TESTPOINT=$(readlink -f "${CURDIR}/.libs/libpause_sessiond.so")

SH_TAP=1

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"

FULL_LTTNG_BIN="${TESTDIR}/../src/bin/lttng/${LTTNG_BIN}"
FULL_LTTNG_SESSIOND_BIN="${TESTDIR}/../src/bin/lttng-sessiond/lttng-sessiond"

KERNEL_DISCARD_NUM_TESTS=10
KERNEL_DISCARD_MAX_BUCKET_NUM_TESTS=7
KERNEL_NUM_TESTS=$((KERNEL_DISCARD_NUM_TESTS + KERNEL_DISCARD_MAX_BUCKET_NUM_TESTS))

NUM_TESTS=$KERNEL_NUM_TESTS

plan_tests $NUM_TESTS

function trigger_get_discarded_notif_number()
{
	local trigger_name="$1"
	local list_triggers_stdout

	list_triggers_stdout=$(mktemp -t "list_triggers_stdout.XXXXXX")

	"$FULL_LTTNG_BIN" list-triggers > "$list_triggers_stdout"

	cat "$list_triggers_stdout" | grep -A7 "$trigger_name" | grep -A2 "event rule matches" | tail -1 | grep --quiet "errors: none"
	ret=$?

	if [ "$ret" -eq "0" ]; then
		notif_nb="0"
	else
		notif_nb=$(cat "$list_triggers_stdout" | grep -A7 "$trigger_name" | grep "discarded tracer messages" | cut -d' ' -f10)
	fi

	rm -f "$list_triggers_stdout"

	# Printing the value to that the caller can get it back.
	echo "$notif_nb"
}

function test_kernel_notifier_discarded_count
{
	local sessiond_pipe=()
	local trigger_name="my_trigger"
	local list_triggers_stdout

	list_triggers_stdout=$(mktemp -t "list_triggers_stdout.XXXXXX")

	# Used on sessiond launch.
	LTTNG_SESSIOND_ENV_VARS="LTTNG_TESTPOINT_ENABLE=1 \
		NOTIFIER_PAUSE_PIPE_PATH=${TESTPOINT_PIPE_PATH} \
		LD_PRELOAD=${TESTPOINT}"

	diag "Kernel event notifer error counter"

	if ! start_lttng_sessiond; then
		skip 0 "Failed to start sessiond" $((KERNEL_DISCARD_NUM_TESTS - 1))
		return
	fi

	# This is needed since the testpoint creates a pipe with the sessiond
	# type suffixed.
	for f in "$TESTPOINT_BASE_PATH"*; do
		sessiond_pipe+=("$f")
	done

	lttng_add_trigger_ok "$trigger_name" \
		--condition event-rule-matches --type=kernel --name=lttng_test_filter_event \
		--action notify

	trigger_discarded_nb=$(trigger_get_discarded_notif_number "$trigger_name")
	is "$trigger_discarded_nb" 0 "No discarded tracer notification"

	# Stop consumption of notifier tracer notifications.
	diag "Pause consumption of tracer messages"
	echo -n 1 > "$sessiond_pipe"

	# The notifier ring buffer configuration is currently made of 16 4096
	# bytes subbuffers. Each kernel notification is at least 42 bytes long.
	# To fill it, we need to generate (16 * 4096)/42 = 1561 notifications.
	# That number is a bit larger than what we need since some of the space
	# is lost in subbuffer boundaries.
	echo -n "2000" > /proc/lttng-test-filter-event

	# Confirm that the number of tracer notifications discarded is non-zero.
	trigger_discarded_nb=$(trigger_get_discarded_notif_number "$trigger_name")
	isnt "$trigger_discarded_nb" 0 "Discarded tracer notification number non-zero ($trigger_discarded_nb) as expected"

	lttng_remove_trigger_ok "$trigger_name"

	# Confirm that no notifier is enabled.
	list_triggers_line_count=$("$FULL_LTTNG_BIN" list-triggers | wc -l)
	is "$list_triggers_line_count" "0" "No \`event-rule-matches\` kernel notifier enabled as expected"

	# Enable another notifier and list it to confirm the counter was cleared.
	lttng_add_trigger_ok "$trigger_name" \
		--condition event-rule-matches --type=kernel --name=lttng_test_filter_event \
		--action notify

	trigger_discarded_nb=$(trigger_get_discarded_notif_number "$trigger_name")
	is "$trigger_discarded_nb" 0 "No discarded tracer notification"

	lttng_remove_trigger_ok "$trigger_name"

	stop_lttng_sessiond

	unset LTTNG_SESSIOND_ENV_VARS

	rm -f "$list_triggers_stdout"
}

function test_kernel_notifier_discarded_count_max_bucket
{
	diag "Kernel event notifer error counter bucket limit"

	if ! start_lttng_sessiond "" "--event-notifier-error-buffer-size-kernel=3"; then
		skip 0 "Failed to start sessiond" $((KERNEL_DISCARD_MAX_BUCKET_NUM_TESTS - 1))
		return
	fi

	for i in $(seq 3); do
		lttng_add_trigger_ok "$i" \
			--condition event-rule-matches --type=kernel --name="my_event_that_doesnt_need_to_really_exist_$i" \
			--action notify
	done

	for i in $(seq 4 5); do
		lttng_add_trigger_fail "$i" \
			--condition event-rule-matches --type=kernel --name="my_event_that_doesnt_need_to_really_exist_$i" \
			--action notify
	done

	stop_lttng_sessiond
}

check_skip_kernel_test "$KERNEL_NUM_TESTS" "Skipping kernel notification tests." ||
{

	validate_lttng_modules_present

	modprobe lttng-test

	test_kernel_notifier_discarded_count
	test_kernel_notifier_discarded_count_max_bucket

	modprobe --remove lttng-test

	rm -rf "${sessiond_pipe[@]}" 2> /dev/null

}

rm -rf "$TEST_TMPDIR"
