#!/bin/bash
#
# SPDX-FileCopyrightText: 2017 Jonathan Rajotte-Julien <jonathan.rajotte-julien@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../../

TESTAPP_STATE_PATH=$(mktemp -u -t "tmp.test_notif_kernel_instrumentation_application_state.XXXXXXXXXX")

NUM_TESTS=13

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"
# shellcheck source=./util_event_generator.sh
source "$CURDIR/util_event_generator.sh"

function test_kernel_instrumentation_notification
{
	kernel_event_generator generate_filter_events "$TESTAPP_STATE_PATH" &
	APP_PID=$!

	"$CURDIR/notification" 4 LTTNG_DOMAIN_KERNEL $APP_PID \
		"$TESTAPP_STATE_PATH"

	kill -SIGUSR2 $APP_PID
	wait $APP_PID 2> /dev/null
}

check_skip_kernel_test &&
{
	plan_skip_all "Skipping all tests."
	exit 0
}

validate_lttng_modules_present

modprobe lttng-test

start_lttng_sessiond_notap

test_kernel_instrumentation_notification

stop_lttng_sessiond_notap
rmmod lttng-test

rm -f "$TESTAPP_STATE_PATH"
