#!/bin/sh
#
# SPDX-FileCopyrightText: 2013 Jérémie Galarneau <jeremie.galarneau@efficios.com>
#
# SPDX-License-Identifier: GPL-2.0-only
#

CURDIR=$(dirname $0)/
ROOTDIR=$CURDIR/../..

$CURDIR/ini_config $CURDIR/sample.ini
