#!/bin/bash
#
# SPDX-FileCopyrightText: 2019 Michael Jeanson <mjeanson@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="Kernel tracer - Namespace contexts"

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../..

TESTS_PER_NS=13

NUM_TESTS=$((TESTS_PER_NS * 8))

source "$TESTDIR/utils/utils.sh"

# MUST set TESTDIR before calling those functions
function add_context_kernel_skip_ok()
{
	local session_name=$1
	local channel_name=$2
	local context_name=$3
	local skip_num=$4

	local ret

	_run_lttng_cmd "$(lttng_client_log_file)" "$(lttng_client_err_file)" add-context -k \
		-s "$session_name" -c "$channel_name" -t "$context_name"
	ret=$?

	if [ "$ret" == "4" ]; then
		skip 0 "Current kernel doesn't implement '$context_name' context" $((skip_num + 1))
	else
		ok $ret "Add context command for type: $context_name"
	fi

	return $ret
}

function enable_kernel_lttng_event_filter_ok()
{
	local session_name=$1
	local syscall_name=$2
	local channel_name=$3
	local filter=$4

	_run_lttng_cmd "$(lttng_client_log_file)" "$(lttng_client_err_file)" enable-event -k \
		-c "$channel_name" -s "$session_name" --syscall "$syscall_name" \
		-f "$filter"

	ok $? "Add syscall with filter"
}

function test_ns()
{
	local ns=$1

	local session_name="${ns}_ns"
	local chan_name="${ns}_ns"
	local context_name="${ns}_ns"

	local trace_path
	local ns_inode

	# Check if the kernel has support for this ns type
	if [ ! -f "/proc/$$/ns/$ns" ]; then
		skip 0 "System has no $ns namespace support" $TESTS_PER_NS
		return
	fi

	# Get the current ns inode number
	ns_inode=$(stat -c '%i' -L "/proc/$$/ns/$ns")
	ok $? "Get current $ns namespace inode: $ns_inode"

	trace_path=$(mktemp -d -t "tmp.${FUNCNAME[0]}_trace_path.XXXXXX")

	lttng_modules_loaded_fail
	start_lttng_sessiond

	create_lttng_session_ok "$session_name" "$trace_path"
	enable_kernel_lttng_channel_ok "$session_name" "$chan_name"
	add_context_kernel_skip_ok "$session_name" "$chan_name" "$context_name" 4
	if [ "$?" != "4" ]; then
		enable_kernel_lttng_event_filter_ok "$session_name" "read" "$chan_name" "\$ctx.$context_name == $ns_inode"
		start_lttng_tracing_ok "$session_name"

		# Make sure there is at least one read syscall
		cat /proc/cmdline >/dev/null

		stop_lttng_tracing_ok "$session_name"

		# Check that the events contain the right namespace inode number
		validate_trace "${ns}_ns = $ns_inode" "$trace_path"
	fi

	destroy_lttng_session_ok "$session_name"
	stop_lttng_sessiond
	lttng_modules_loaded_fail

	rm -rf "$trace_path"
}


plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"


check_skip_kernel_test "$NUM_TESTS" "Skipping all tests." && exit 0

system_has_ns=0
if [ -d "/proc/$$/ns" ]; then
	system_has_ns=1
fi

skip $system_has_ns "System does not support namespaces" $NUM_TESTS && exit 0


validate_lttng_modules_present

test_ns cgroup
test_ns ipc
test_ns mnt
test_ns net
test_ns pid
test_ns time
test_ns user
test_ns uts
