#!/bin/bash
#
# Copyright (C) - 2017 Erica Bugden <erica.bugden@efficios.com>
# Copyright (C) - 2017 Francis Deslauriers <francis.deslauriers@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

TEST_DESC="Userspace probe - Testing userspace probe on ELF symbol"

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../..
ELF_TEST_BIN_DIR="$TESTDIR/utils/testapp/userspace-probe-elf-binary/"
ELF_TEST_BIN_NAME="userspace-probe-elf-binary"
ELF_TEST_BIN="$ELF_TEST_BIN_DIR/$ELF_TEST_BIN_NAME"
SDT_TEST_BIN_DIR="$TESTDIR/utils/testapp/userspace-probe-sdt-binary/.libs/"
SDT_TEST_BIN_NAME="userspace-probe-sdt-binary"
SDT_TEST_BIN="$SDT_TEST_BIN_DIR/$SDT_TEST_BIN_NAME"
SESSION_NAME=userspace_probe_test_session
PROBE_EVENT_NAME=userspace_probe_test_event
NUM_TESTS=113
OUTPUT_DEST=/dev/null
ERROR_OUTPUT_DEST=/dev/null

source "$TESTDIR/utils/utils.sh"

function validate_list()
{
	local session_name=$1
	local event_name=$2

	out=$("$TESTDIR/../src/bin/lttng/$LTTNG_BIN" list "$session_name" | grep "$event_name")
	if [ -z "$out" ]; then
		fail "Validate userspace probe listing"
		diag "$event_name not found when listing $session_name"
	else
		pass "Validate userspace probe listing. Found $event_name."
	fi
}

function enable_kernel_lttng_userspace_probe_event ()
{
	local expected_to_fail="$1"
	local sess_name="$2"
	local target="$3"
	local event_name="$4"

	"$TESTDIR/../src/bin/lttng/$LTTNG_BIN" enable-event --kernel --userspace-probe="$target" "$event_name" -s "$sess_name" > "$OUTPUT_DEST" 2> "$ERROR_OUTPUT_DEST"
	ret=$?
	if [[ $expected_to_fail -eq "1" ]]; then
		test $ret -ne "0"
		ok $? "Enable kernel event $target for session $sess_name failed as expected"
	else
		ok $ret "Enable kernel event $target for session $sess_name"
	fi
}

function enable_kernel_lttng_userspace_probe_event_fail ()
{
	enable_kernel_lttng_userspace_probe_event 1 "$@"
}

function enable_kernel_lttng_userspace_probe_event_ok ()
{
	enable_kernel_lttng_userspace_probe_event 0 "$@"
}

function test_userspace_probe_enable_file_noexist ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_file_noexist"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="elf:/etc/file-not-exist:$ELF_SYMBOL"

	diag "Userspace probe enable on non-existant file"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME $ENABLE_EXPR $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_file_not_elf ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_file_not_elf"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="elf:/etc/passwd:$ELF_SYMBOL"

	diag "Userspace probe enable on a non ELF file"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME $ENABLE_EXPR $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_elf_missing_symbol_name ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_elf_missing_symbol"
	ENABLE_EXPR="elf:$ELF_TEST_BIN:"

	diag "Userspace probe enable with unspecified ELF symbol"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_elf_nonexistant_symbol ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_elf_nonexistant_symbol"
	ELF_SYMBOL="function_doesnt_exist"
	ENABLE_EXPR="elf:$ELF_TEST_BIN:$ELF_SYMBOL"

	diag "Userspace probe enable with nonexistant ELF symbol"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_elf_symbol_not_function ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_elf_symbol_not_function"
	ELF_SYMBOL="not_a_function"
	ENABLE_EXPR="elf:$ELF_TEST_BIN:$ELF_SYMBOL"

	diag "Userspace probe enable with non-function ELF symbol"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_implicit_probe_type ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_implicit_probe_type"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="$ELF_TEST_BIN:$ELF_SYMBOL"

	diag "Userspace probe enabled successfully with implicit probe type"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	validate_list  $SESSION_NAME $ELF_SYMBOL
	validate_list  $SESSION_NAME $ELF_TEST_BIN_NAME
	validate_list  $SESSION_NAME "ELF"
	validate_list  $SESSION_NAME "Function"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_elf_symbol_exists ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_elf_symbol_exists"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="elf:$ELF_TEST_BIN:$ELF_SYMBOL"

	diag "Userspace probe enabled successfully"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	validate_list  $SESSION_NAME $ELF_SYMBOL
	validate_list  $SESSION_NAME $ELF_TEST_BIN_NAME
	validate_list  $SESSION_NAME "ELF"
	validate_list  $SESSION_NAME "Function"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_in_path ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_in_path"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="elf:$ELF_TEST_BIN_NAME:$ELF_SYMBOL"

	diag "Userspace probe on binary in PATH enabled successfully"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	# Save old PATH and add the test directory to the PATH.
	OLDPATH="$PATH"
	export PATH="$PATH:$(realpath $ELF_TEST_BIN_DIR)"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	validate_list  $SESSION_NAME $ELF_SYMBOL
	validate_list  $SESSION_NAME $ELF_TEST_BIN_NAME
	validate_list  $SESSION_NAME "ELF"
	validate_list  $SESSION_NAME "Function"

	# Reset the previously saved PATH.
	export PATH="$OLDPATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_full_path ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userspace_probe_enable_full_path"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="elf:$(realpath $ELF_TEST_BIN):$ELF_SYMBOL"
	diag "Userspace probe with full path enabled successfully"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	validate_list  $SESSION_NAME $ELF_SYMBOL
	validate_list  $SESSION_NAME $ELF_TEST_BIN_NAME
	validate_list  $SESSION_NAME "ELF"
	validate_list  $SESSION_NAME "Function"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_elf ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="elf:$ELF_TEST_BIN:$ELF_SYMBOL"

	diag "Userspace probe enabled and traced"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	eval "$ELF_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_elf_list ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	ELF_SYMBOL="test_function"
	ENABLE_EXPR="elf:$ELF_TEST_BIN:$ELF_SYMBOL"

	diag "Userspace probe ELF enabled and listed"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	validate_list  $SESSION_NAME $PROBE_EVENT_NAME
	validate_list  $SESSION_NAME $ELF_SYMBOL
	validate_list  $SESSION_NAME $ELF_TEST_BIN_NAME
	validate_list  $SESSION_NAME "ELF"
	validate_list  $SESSION_NAME "Function"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt ()
{
	TRACE_PATH=$(mktemp -d)
	PROVIDER="foobar"
	PROBE="tp1"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe on SDT tracepoint enabled and traced"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	eval "$SDT_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt_list ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp1"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe SDT enabled and listed"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	validate_list  $SESSION_NAME $PROBE_EVENT_NAME
	validate_list  $SESSION_NAME $PROVIDER
	validate_list  $SESSION_NAME $PROBE
	validate_list  $SESSION_NAME $SDT_TEST_BIN_NAME
	validate_list  $SESSION_NAME "SDT"
	validate_list  $SESSION_NAME "Tracepoint"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_sdt_nonexistant_provider ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="not_provider"
	PROBE="tp1"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on tracepoint non existant provider"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_sdt_nonexistant_probe ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="not_a_tracepoint"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on non existant probe"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_enable_sdt_with_sema ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp_with_semaphore"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on non existant probe"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_fail $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt_one_probe ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp1"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on tracepoint with one callsite"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	eval "$SDT_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt_two_probes ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp2"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on tracepoint with two callsites"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	eval "$SDT_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt_in_shared_object ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp_in_shared_object"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN_DIR/libfoo.so:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on tracepoint in shared object"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	eval "$SDT_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt_in_shared_object_dlopen ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp_in_dlopen"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN_DIR/libbar.so:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on tracepoint in dlopen()ed shared object"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	eval "$SDT_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt_in_shared_object_ldpreload ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp_in_ldpreload"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN_DIR/libzzz.so:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on tracepoint in an LD_PRELOADed shared object"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	LD_PRELOAD="$SDT_TEST_BIN_DIR/libzzz.so" eval "$SDT_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

function test_userspace_probe_sdt_with_arg ()
{
	TRACE_PATH=$(mktemp -d)
	SESSION_NAME="test_userprobe"
	PROVIDER="foobar"
	PROBE="tp_with_arg"
	ENABLE_EXPR="sdt:$SDT_TEST_BIN:$PROVIDER:$PROBE"

	diag "Userspace probe SDT on tracepoint with argument"

	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"

	enable_kernel_lttng_userspace_probe_event_ok $SESSION_NAME "$ENABLE_EXPR" $PROBE_EVENT_NAME

	start_lttng_tracing_ok $SESSION_NAME
	eval "$SDT_TEST_BIN"  > /dev/null
	stop_lttng_tracing_ok $SESSION_NAME

	validate_trace $PROBE_EVENT_NAME "$TRACE_PATH"

	destroy_lttng_session_ok $SESSION_NAME

	rm -rf "$TRACE_PATH"
}

plan_tests $NUM_TESTS
print_test_banner "$TEST_DESC"

if [ "$(id -u)" == "0" ]; then
	isroot=1
else
	isroot=0
fi

skip $isroot "Root access is needed. Skipping all tests." $NUM_TESTS ||
{
	start_lttng_sessiond

	# Unsuccessful event enabling
	test_userspace_probe_enable_file_noexist
	test_userspace_probe_enable_file_not_elf

	test_userspace_probe_enable_elf_missing_symbol_name
	test_userspace_probe_enable_elf_nonexistant_symbol
	test_userspace_probe_enable_elf_symbol_not_function

	test_userspace_probe_enable_sdt_nonexistant_provider
	test_userspace_probe_enable_sdt_nonexistant_probe
	test_userspace_probe_enable_sdt_with_sema

	# Successful event enabling
	test_userspace_probe_enable_implicit_probe_type
	test_userspace_probe_enable_in_path
	test_userspace_probe_enable_full_path

	test_userspace_probe_enable_elf_symbol_exists

	### Successful event tracing
	test_userspace_probe_elf

	#test_userspace_probe_elf_cxx

	test_userspace_probe_sdt_one_probe
	test_userspace_probe_sdt_two_probes
	test_userspace_probe_sdt_with_arg
	test_userspace_probe_sdt_in_shared_object
	test_userspace_probe_sdt_in_shared_object_dlopen
	test_userspace_probe_sdt_in_shared_object_ldpreload

	# Successful listing of event
	test_userspace_probe_sdt_list
	test_userspace_probe_elf_list

	stop_lttng_sessiond
}
