#!/bin/bash
#
# Copyright (C) 2013 Julien Desfossez <jdesfossez@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname $0)/
NR_SNAPSHOT=1000
TESTDIR=$CURDIR/../../..
TEST_BIN="ust_test"

source $TESTDIR/utils/utils.sh

if [ ! -x "$CURDIR/$TEST_BIN" ]; then
	BAIL_OUT "No UST test found: $TEST_BIN"
fi

exec $CURDIR/$TEST_BIN $NR_SNAPSHOT
