#!/bin/bash
#
# Copyright (C) - 2013 David Goulet <dgoulet@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
TEST_DESC="Streaming - Snapshot UST tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../..
EVENT_NAME="tp:tptest"
PID_RELAYD=0
SESSION_NAME=""
CHANNEL_NAME="chan1"
BIN_NAME="gen-nevents"
TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME/$TESTAPP_NAME"
NR_ITER=2000000
NR_USEC_WAIT=100
APPS_PID=


NUM_TESTS=49

source $TESTDIR/utils/utils.sh

if [ ! -x "$TESTAPP_BIN" ]; then
	BAIL_OUT "No UST events binary detected."
fi

if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
	override_base_command_ssh $REMOTE_RELAYD_HOST $REMOTE_RELAYD_USER $REMOTE_RELAYD_ID_FILE
fi

TRACE_PATH=$($BASE_COMMAND "mktemp -d")

# Start trace application and return once one event has been hit.
function start_test_app()
{
	local tmp_file=$(mktemp -u)

	# Start application with a temporary file.
	$TESTAPP_BIN $NR_ITER $NR_USEC_WAIT $tmp_file &
	ret=$?
	APPS_PID="${APPS_PID} ${!}"
	ok $ret "Start application to trace"

	# Wait for the application file to appear indicating that at least one
	# tracepoint has been fired.
	while [ ! -f "$tmp_file" ]; do
		sleep 0.5
	done
	diag "Removing test app temporary file $tmp_file"
	rm -f $tmp_file
}

function stop_test_apps()
{
	diag "Stopping $TESTAPP_NAME"
	for p in ${APPS_PID}; do
		kill ${p}
		wait ${p} 2>/dev/null
	done
	APPS_PID=
}

# Test a snapshot using a default name for the output destination.
function test_ust_default_name_with_del()
{
	diag "Test UST snapshot streaming with default name with delete output"

	local host="localhost"

	if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
		host=$REMOTE_RELAYD_HOST
	fi

	create_lttng_session_no_output $SESSION_NAME
	enable_lttng_mmap_overwrite_ust_channel $SESSION_NAME $CHANNEL_NAME
	enable_ust_lttng_event_ok $SESSION_NAME $EVENT_NAME $CHANNEL_NAME
	start_lttng_tracing_ok $SESSION_NAME

	start_test_app

	lttng_snapshot_add_output_ok $SESSION_NAME "net://$host"
	lttng_snapshot_record $SESSION_NAME

	# Validate test
	validate_trace_remote_support $EVENT_NAME $TRACE_PATH/$HOSTNAME/snapshot-1*
	if [ $? -ne 0 ]; then
		stop_test_apps
		return $?
	fi

	lttng_snapshot_del_output_ok $SESSION_NAME 1
	lttng_snapshot_add_output_ok $SESSION_NAME "net://$host"
	lttng_snapshot_record $SESSION_NAME

	# Validate test with the next ID since a del output was done prior.
	validate_trace_remote_support $EVENT_NAME $TRACE_PATH/$HOSTNAME/snapshot-2*
	if [ $? -ne 0 ]; then
		stop_test_apps
		return $?
	fi

	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME

	stop_test_apps

	return 0
}

# Test a snapshot using a default name for the output destination.
function test_ust_default_name()
{
	local host="localhost"

	if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
		host=$REMOTE_RELAYD_HOST
	fi

	diag "Test UST snapshot streaming with default name"
	create_lttng_session_no_output $SESSION_NAME
	enable_lttng_mmap_overwrite_ust_channel $SESSION_NAME $CHANNEL_NAME
	enable_ust_lttng_event_ok $SESSION_NAME $EVENT_NAME $CHANNEL_NAME
	start_lttng_tracing_ok $SESSION_NAME

	start_test_app

	lttng_snapshot_add_output_ok $SESSION_NAME "net://$host"
	lttng_snapshot_record $SESSION_NAME
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME
	# Validate test
	validate_trace_remote_support $EVENT_NAME $TRACE_PATH/$HOSTNAME/snapshot-1*
	out=$?

	stop_test_apps

	return $out
}

function test_ust_default_name_custom_uri()
{
	local host="localhost"

	if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
		host=$REMOTE_RELAYD_HOST
	fi

	diag "Test UST snapshot streaming with default name with custom URL"
	create_lttng_session_no_output $SESSION_NAME
	enable_lttng_mmap_overwrite_ust_channel $SESSION_NAME $CHANNEL_NAME
	enable_ust_lttng_event_ok $SESSION_NAME $EVENT_NAME $CHANNEL_NAME
	start_lttng_tracing_ok $SESSION_NAME

	start_test_app

	lttng_snapshot_add_output_ok $SESSION_NAME "-C tcp://$host:5342 -D tcp://$host:5343"
	lttng_snapshot_record $SESSION_NAME
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME
	# Validate test
	validate_trace_remote_support $EVENT_NAME $TRACE_PATH/$HOSTNAME/snapshot-1*
	out=$?

	stop_test_apps

	return $out
}

# Test a snapshot using a custom name for the output destination.
function test_ust_custom_name()
{
	local out
	local name="asnapshotname"
	local host="localhost"

	if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
		host=$REMOTE_RELAYD_HOST
	fi

	diag "Test UST snapshot streaming with custom name"
	create_lttng_session_no_output $SESSION_NAME
	enable_lttng_mmap_overwrite_ust_channel $SESSION_NAME $CHANNEL_NAME
	enable_ust_lttng_event_ok $SESSION_NAME $EVENT_NAME $CHANNEL_NAME
	start_lttng_tracing_ok $SESSION_NAME

	start_test_app

	lttng_snapshot_add_output_ok $SESSION_NAME "net://$host" $name
	lttng_snapshot_record $SESSION_NAME
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME

	if ($BASE_COMMAND "ls $TRACE_PATH/$HOSTNAME/$name* &> /dev/null"); then
		ok 0 "Custom name snapshot exists"
		# Validate test
		validate_trace_remote_support $EVENT_NAME $TRACE_PATH/$HOSTNAME/$name-*
		out=$?
	else
		fail "No custom name snapshot found"
		out=1
	fi

	stop_test_apps

	return $out
}

plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

start_lttng_relayd_remote_support "-o $TRACE_PATH"
start_lttng_sessiond

tests=( test_ust_default_name_with_del test_ust_default_name test_ust_custom_name test_ust_default_name_custom_uri )

for fct_test in ${tests[@]};
do
	SESSION_NAME=$(randstring 16 0)
	${fct_test}
	if [ $? -eq 0 ]; then
		# Only delete if successful
		$BASE_COMMAND "rm -rf $TRACE_PATH"
	else
		break
	fi
done

stop_lttng_sessiond
stop_lttng_relayd_remote_support
reestablish_base_command
