#!/bin/bash
#
# Copyright (C) - 2012 David Goulet <dgoulet@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
NR_ITER=30
TEST_DESC="UST tracer - Generate $NR_ITER process"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../..
TEST_BIN_NAME="gen-events-time"
SESSION_NAME="ust-nprocesses"
EVENT_NAME="ust_gen_event:tptest"
TEST_WAIT_SEC=5
NUM_TESTS=9

source $TESTDIR/utils/utils.sh

if [ ! -x "$CURDIR/$TEST_BIN_NAME" ]; then
	BAIL_OUT "No UST $TEST_BIN_NAME binary detected."
fi

# MUST set TESTDIR before calling those functions

plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

start_lttng_sessiond

# Start test for 1000 seconds

for i in `seq 1 $NR_ITER`
do
	./$CURDIR/$TEST_BIN_NAME 1000 >/dev/null 2>&1 &
done

reg_app_count=0
while [ $reg_app_count -ne $NR_ITER ]; do
	listing=$($TESTDIR/../src/bin/lttng/$LTTNG_BIN list -u)
	reg_app_count=$(echo -n $listing | sed "s/$TEST_BIN_NAME/$TEST_BIN_NAME\n/g" | grep "$TEST_BIN_NAME" | wc -l)
done

pass "Trace validation"

TRACE_PATH=$(mktemp -d)

create_lttng_session $SESSION_NAME $TRACE_PATH

enable_ust_lttng_event $SESSION_NAME $EVENT_NAME
start_lttng_tracing $SESSION_NAME

diag "Sleeping $TEST_WAIT_SEC seconds for tracing to start everywhere"
diag "Warning: this arbitrary time can make the test fail on slower system"

sleep $TEST_WAIT_SEC

stop_lttng_tracing $SESSION_NAME
destroy_lttng_session $SESSION_NAME

rm -rf $TRACE_PATH

while [ -n "$(pidof $TEST_BIN_NAME)" ]; do
	killall -q $TEST_BIN_NAME >/dev/null 2>&1
	sleep 0.5
done


pass "Kill all spawned applications"

stop_lttng_sessiond
