#!/bin/bash
#
# Copyright (C) - 2017 Julien Desfossez <jdesfossez@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
TEST_DESC="Rotation - Kernel tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../..
EVENT_NAME="lttng_test_filter_event"

TRACE_PATH=$(mktemp -d)

NUM_TESTS=60

source $TESTDIR/utils/utils.sh
source $CURDIR/rotate_utils.sh

function rotate_kernel_test ()
{
	local_path=$1

	lttng_enable_kernel_event $SESSION_NAME $EVENT_NAME
	start_lttng_tracing_ok $SESSION_NAME

	today=$(date +%Y%m%d)
	# First chunk contains 10 events.
	echo -n "10" > /proc/lttng-test-filter-event
	rotate_session_ok $SESSION_NAME

	# Second chunk contains 20 events.
	echo -n "20" > /proc/lttng-test-filter-event
	stop_lttng_tracing_ok $SESSION_NAME

	# Third chunk contains no event (rotate after stop).
	rotate_session_ok $SESSION_NAME

	destroy_lttng_session_ok $SESSION_NAME

	validate_test_chunks $local_path $today kernel kernel 0
}

function test_kernel_streaming ()
{
	diag "Test kernel streaming with session rotation"
	create_lttng_session_uri $SESSION_NAME net://localhost
	rotate_kernel_test "${TRACE_PATH}/${HOSTNAME}/${SESSION_NAME}*/archives"
}

function test_kernel_local ()
{
	diag "Test kernel local with session rotation"
	create_lttng_session_ok $SESSION_NAME $TRACE_PATH

	rotate_kernel_test "${TRACE_PATH}/archives"
}

function test_kernel_local_timer ()
{
	diag "Test kernel local with session rotation timer"
	create_lttng_session_ok $SESSION_NAME $TRACE_PATH
	lttng_enable_kernel_event $SESSION_NAME $EVENT_NAME
	lttng_enable_rotation_timer_ok $SESSION_NAME 500ms
	start_lttng_tracing_ok $SESSION_NAME

	rotate_timer_test "${TRACE_PATH}/archives" 0
}

function test_kernel_streaming_timer ()
{
	diag "Test kernel remote with session rotation timer"
	create_lttng_session_uri $SESSION_NAME net://localhost
	lttng_enable_kernel_event $SESSION_NAME $EVENT_NAME
	lttng_enable_rotation_timer_ok $SESSION_NAME 500ms
	start_lttng_tracing_ok $SESSION_NAME

	rotate_timer_test "${TRACE_PATH}/${HOSTNAME}/${SESSION_NAME}*/archives" 0
}

plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

if [ "$(id -u)" == "0" ]; then
	isroot=1
else
	isroot=0
fi

skip $isroot "Root access is needed. Skipping all kernel streaming tests." $NUM_TESTS ||
{
	validate_lttng_modules_present

	start_lttng_relayd "-o $TRACE_PATH"
	start_lttng_sessiond
	modprobe lttng-test

	tests=( test_kernel_streaming test_kernel_local test_kernel_local_timer test_kernel_streaming_timer)

	for fct_test in ${tests[@]};
	do
		SESSION_NAME=$(randstring 16 0)
		${fct_test}
		clean_path $TRACE_PATH
	done

	rmmod lttng-test
	stop_lttng_sessiond
	stop_lttng_relayd
}

rm -rf $TRACE_PATH
