#!/bin/bash
#
# Copyright (C) - 2018 Jérémie Galarneau <jdesfossez@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
TEST_DESC="Rotation - Schedule API"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../..

SESSION_NAME="my_session"
TRACE_PATH=$(mktemp -d)

source $TESTDIR/utils/utils.sh

print_test_banner "$TEST_DESC"

start_lttng_sessiond_notap

create_lttng_session_notap $SESSION_NAME $TRACE_PATH

# The actual test is a native application as it tests the liblttng-ctl API
$CURDIR/schedule_api $SESSION_NAME

destroy_lttng_session_notap $SESSION_NAME
stop_lttng_sessiond_notap

# Remove tmp dir
rm -rf $TRACE_PATH
