#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (c) 2023 Olivier Dion <odion@efficios.com>

# Augment this list incrementally when a shell script passes shellcheck.
#
# All file must be relative to the test directory.
files=(
    meta/test_shellcheck
    regression/ust/multi-session/test_multi_session
    regression/ust/overlap/test_overlap
    utils/utils.sh
)

TESTDIR=$(dirname "$0")/..

# shellcheck source-path=SCRIPTDIR/..
source "$TESTDIR/utils/utils.sh"

function shellcheck_ok() {
    shellcheck --external-sources "$1"
    ok $? "Checking '$(get_path_from_top_dir "$1")'"
}

plan_tests "${#files[@]}"

for f in "${files[@]}";
do
    shellcheck_ok "$TESTDIR/$f"
done
