#!/bin/bash
#
# SPDX-FileCopyrightText: 2013 Julien Desfossez <julien.desfossez@efficios.com>
# SPDX-FileCopyrightText: 2013 David Goulet <dgoulet@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="Live - Kernel space tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../../
NR_ITER=1
NR_USEC_WAIT=1
DELAY_USEC=2000000

SESSION_NAME="live"
EVENT_NAME="lttng_test_filter_event"

TRACE_PATH=$(mktemp -d -t tmp.test_live_kernel_trace_path.XXXXXX)

DIR=$(readlink -f $TESTDIR)

source $TESTDIR/utils/utils.sh

function setup_live_tracing()
{
	# Create session with default path
	$TESTDIR/../src/bin/lttng/$LTTNG_BIN create $SESSION_NAME --live $DELAY_USEC \
		-U net://localhost >/dev/null 2>&1

	$TESTDIR/../src/bin/lttng/$LTTNG_BIN enable-event "$EVENT_NAME" -s $SESSION_NAME -k >/dev/null 2>&1
	$TESTDIR/../src/bin/lttng/$LTTNG_BIN start $SESSION_NAME >/dev/null 2>&1
}

function clean_live_tracing()
{
	$TESTDIR/../src/bin/lttng/$LTTNG_BIN stop $SESSION_NAME >/dev/null 2>&1
	$TESTDIR/../src/bin/lttng/$LTTNG_BIN destroy $SESSION_NAME >/dev/null 2>&1
	rm -rf $TRACE_PATH
}

check_skip_kernel_test &&
{
	plan_skip_all "Skipping all tests."
	exit 0
}

modprobe lttng-test
tap_disable

start_lttng_sessiond_notap
start_lttng_relayd_notap "-o $TRACE_PATH"

setup_live_tracing

echo -n "1" > /proc/lttng-test-filter-event

# Start the live test
$TESTDIR/regression/tools/live/live_test

clean_live_tracing

stop_lttng_relayd_notap
modprobe --remove lttng-test
stop_lttng_sessiond_notap
