#!/bin/bash
#
# Copyright (C) - 2013 Julien Desfossez <julien.desfossez@efficios.com>
#                      David Goulet <dgoulet@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

TEST_DESC="Live - Kernel space tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../../
DELAY_USEC=2000000

SESSION_NAME="live"
EVENT_NAME="sched_switch"

DIR=$(readlink -f $TESTDIR)

NUM_TESTS=10

source $TESTDIR/utils/utils.sh

if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
	override_base_command_ssh $REMOTE_RELAYD_HOST $REMOTE_RELAYD_USER $REMOTE_RELAYD_ID_FILE
	RELAYD_HOST="$REMOTE_RELAYD_HOST"
fi

TRACE_PATH=$($BASE_COMMAND "mktemp -d")

# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

function setup_live_tracing()
{
	# Create session with default path
	local host="localhost"

	if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
		host=$REMOTE_RELAYD_HOST
	fi

	create_lttng_session_ok $SESSION_NAME "" "--live $DELAY_USEC -U net://$host"
	lttng_enable_kernel_event $SESSION_NAME $EVENT_NAME
	start_lttng_tracing_ok $SESSION_NAME
}

function clean_live_tracing()
{
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME
}

# Need root access for kernel tracing.
if [ "$(id -u)" == "0" ]; then
	isroot=1
else
	isroot=0
fi

skip $isroot "Root access is needed. Skipping all tests." $NUM_TESTS ||
{
	start_lttng_sessiond
	start_lttng_relayd_remote_support "-o $TRACE_PATH"

	setup_live_tracing

	# Just hit some events
	sleep 2

	clean_live_tracing

	validate_trace_remote_support $EVENT_NAME $TRACE_PATH
	$BASE_COMMAND "rm -rf $TRACE_PATH"

	stop_lttng_sessiond
	stop_lttng_relayd_remote_support
	reestablish_base_command
}
