#!/bin/bash
#
# Copyright (C) 2013 Julien Desfossez <julien.desfossez@efficios.com>
# Copyright (C) 2013 David Goulet <dgoulet@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="Live - User space tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../../
NR_ITER=1
NR_USEC_WAIT=1
DELAY_USEC=2000000
TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME/$TESTAPP_NAME"

SESSION_NAME="live"
EVENT_NAME="tp:tptest"

TRACE_PATH=$(mktemp -d -t tmp.test_test_live_lttng_ust_trace_path.XXXXXX)

DIR=$(readlink -f $TESTDIR)

NUM_TESTS=11

source $TESTDIR/utils/utils.sh

# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

bail_out_if_no_babeltrace

function test_custom_url()
{
	# Create session with custom URL
	$TESTDIR/../src/bin/lttng/$LTTNG_BIN create $SESSION_NAME --live $DELAY_USEC \
		-C tcp://localhost:1819 -D tcp://localhost:9187 >/dev/null 2>&1
	ok $? "Create session in live mode with delay $DELAY_USEC and custom URLs"
}

function setup_live_tracing()
{
	# Create session with default path
	$TESTDIR/../src/bin/lttng/$LTTNG_BIN create $SESSION_NAME --live $DELAY_USEC \
		-U net://localhost >/dev/null 2>&1
	ok $? "Create session in live mode with delay $DELAY_USEC"

	enable_ust_lttng_event_ok $SESSION_NAME $EVENT_NAME
	start_lttng_tracing_ok $SESSION_NAME
}

function clean_live_tracing()
{
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME
}

start_lttng_sessiond
start_lttng_relayd "-o $TRACE_PATH"

setup_live_tracing

$TESTAPP_BIN -i $NR_ITER -w $NR_USEC_WAIT >/dev/null 2>&1

clean_live_tracing

trace_match_only $EVENT_NAME $NR_ITER $TRACE_PATH
rm -rf $TRACE_PATH
stop_lttng_relayd

test_custom_url

stop_lttng_sessiond
