#!/bin/bash
#
# Copyright (C) 2013 Julien Desfossez <julien.desfossez@efficios.com>
# Copyright (C) 2013 David Goulet <dgoulet@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="Live - Kernel space tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../../
DELAY_USEC=2000000

SESSION_NAME="live"
EVENT_NAME="lttng_test_filter_event"

TRACE_PATH=$(mktemp --tmpdir -d tmp.test_lttng_live_kernel_trace_path.XXXXXX)

DIR=$(readlink -f $TESTDIR)

NUM_TESTS=11

source $TESTDIR/utils/utils.sh

# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

function setup_live_tracing()
{
	# Create session with default path
	$TESTDIR/../src/bin/lttng/$LTTNG_BIN create $SESSION_NAME --live $DELAY_USEC \
		-U net://localhost >/dev/null 2>&1
	ok $? "Create session in live mode with delay $DELAY_USEC"

	lttng_enable_kernel_event $SESSION_NAME $EVENT_NAME
	start_lttng_tracing_ok $SESSION_NAME
}

function clean_live_tracing()
{
	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME
}

# Need root access for kernel tracing.
if [ "$(id -u)" == "0" ]; then
	isroot=1
else
	isroot=0
fi

skip $isroot "Root access is needed. Skipping all tests." $NUM_TESTS ||
{
	modprobe lttng-test

	start_lttng_sessiond
	start_lttng_relayd "-o $TRACE_PATH"

	setup_live_tracing

	echo -n "1" > /proc/lttng-test-filter-event

	clean_live_tracing

	validate_trace_path_kernel_network "$TRACE_PATH" "$SESSION_NAME"
	validate_trace $EVENT_NAME $TRACE_PATH
	rm -rf $TRACE_PATH

	stop_lttng_relayd
	stop_lttng_sessiond

	modprobe --remove lttng-test
}
