#!/bin/bash
#
# Copyright (C) - 2013 Julien Desfossez <julien.desfossez@efficios.com>
#                      David Goulet <dgoulet@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

TEST_DESC="Live - Kernel space tracing"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../../
NR_ITER=1
NR_USEC_WAIT=1
DELAY_USEC=2000000

SESSION_NAME="live"
EVENT_NAME="sched_switch"
RELAYD_HOST="localhost"

DIR=$(readlink -f $TESTDIR)

source $TESTDIR/utils/utils.sh

if [[ ! -z "$REMOTE_RELAYD_TEST" ]]; then
	override_base_command_ssh $REMOTE_RELAYD_HOST $REMOTE_RELAYD_USER $REMOTE_RELAYD_ID_FILE
	RELAYD_HOST="$REMOTE_RELAYD_HOST"
fi

TRACE_PATH=$($BASE_COMMAND "mktemp -d")

echo "$TEST_DESC (base command: $BASE_COMMAND)"

function setup_live_tracing()
{
	if [[ $isroot -ne 1 ]]; then
		# Do nothing the test plan is produced by live_test
		return 0
	fi

	# Create session with default path
	# TODO: provide no_tap of utils.sh functions
	#       These cannot be used here because the test plan is produced
	#       by live_test
	$TESTDIR/$LTTNG_PATH_REL/$LTTNG_BIN create $SESSION_NAME --live $DELAY_USEC \
		-U net://$RELAYD_HOST >/dev/null 2>&1

	$TESTDIR/$LTTNG_PATH_REL/$LTTNG_BIN enable-event "$EVENT_NAME" -s $SESSION_NAME -k >/dev/null 2>&1
	$TESTDIR/$LTTNG_PATH_REL/$LTTNG_BIN start $SESSION_NAME >/dev/null 2>&1
}

function clean_live_tracing()
{
	if [[ $isroot -ne 1 ]]; then
		# Do nothing the test plan is produced by live_test
		return 0
	fi

	# TODO: provide no_tap of utils.sh functions
	#       These cannot be used here because the test plan is produced
	#       by live_test
	$TESTDIR/$LTTNG_PATH_REL/$LTTNG_BIN stop $SESSION_NAME >/dev/null 2>&1
	$TESTDIR/$LTTNG_PATH_REL/$LTTNG_BIN destroy $SESSION_NAME >/dev/null 2>&1
}

# Need root access for kernel tracing.
if [ "$(id -u)" == "0" ]; then
	isroot=1
else
	isroot=0
fi

start_lttng_sessiond_notap
# Make sure to listen on all interfaces for the live viewer port
start_lttng_relayd_remote_support_no_tap "-o $TRACE_PATH -L tcp://0.0.0.0:5344"

setup_live_tracing

# Start the live test
# We leave to live_test the check for root based on the third argument
$TESTDIR/regression/tools/live/live_test "$RELAYD_HOST" root

clean_live_tracing

stop_lttng_sessiond_notap
stop_lttng_relayd_remote_support_notap

$BASE_COMMAND "rm -rf $TRACE_PATH"
reestablish_base_command
