#!/bin/bash
#
# Copyright (C) - 2012 Christian Babeux <christian.babeux@efficios.com>
# Copyright (C) - 2014 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License, version 2 only, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

TEST_DESC="Health check - Thread exit"

SESSION_NAME="health_thread_exit"
SESSIOND_PRELOAD=".libs/libhealthexit.so"
TEST_SUFFIX="EXIT"
CURDIR=$(dirname $(readlink -f $0))

# A current design limitation of the lttng-consumerd will cause it to
# hang on shutdown if the timer management thread exits as the teardown
# of channels switches off the channel's timers. The timer thread is
# then expected to purge timer signals and signal when it is done.
# Obviously this state will never be reached as signals are no longer
# being processed. This is not dramatic as this is not what this test
# is meant to test; we only want to make sure the health check signals that
# something went wrong.
KILL_SIGNAL="SIGKILL"

source ${CURDIR}/test_health.sh
