#!/bin/bash
#
# SPDX-FileCopyrightText: 2012 Christian Babeux <christian.babeux@efficios.com>
# SPDX-FileCopyrightText: 2014 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# SPDX-License-Identifier: GPL-2.0-only

CURDIR=$(dirname $(readlink -f $0))
TESTDIR=${CURDIR}/../../..
source $TESTDIR/utils/utils.sh

check_skip_long_regression_tests && {
	plan_skip_all "Long regression tests disabled"
	exit 0
}

TEST_DESC="Health check - Testpoint failure"

SESSION_NAME="health_tp_fail"
SESSIOND_PRELOAD=".libs/libhealthtpfail.so"
TEST_SUFFIX="TP_FAIL"

# A current design limitation of the lttng-consumerd will cause it to
# hang on shutdown if the timer management thread exits as the teardown
# of channels switches off the channel's timers. The timer thread is
# then expected to purge timer signals and signal when it is done.
# Obviously this state will never be reached as signals are no longer
# being processed. This is not dramatic as this is not what this test
# is meant to test; we only want to make sure the health check signals that
# something went wrong.
KILL_SIGNAL="SIGKILL"

source ${CURDIR}/test_health.sh
