#!/bin/bash
#
# SPDX-FileCopyrightText: 2012 Christian Babeux <christian.babeux@efficios.com>
# SPDX-FileCopyrightText: 2014 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname $(readlink -f $0))
TESTDIR=${CURDIR}/../../..
source $TESTDIR/utils/utils.sh

check_skip_long_regression_tests && {
	plan_skip_all "Long regression tests disabled"
	exit 0
}

TEST_DESC="Health check - Thread stall"
SESSION_NAME="health_thread_stall"
SESSIOND_PRELOAD=".libs/libhealthstall.so"
TEST_SUFFIX="STALL"

source ${CURDIR}/test_health.sh
