#!/bin/bash
#
# SPDX-FileCopyrightText: 2012 Christian Babeux <christian.babeux@efficios.com>
# SPDX-FileCopyrightText: 2014 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="Health check - Thread stall"

SESSION_NAME="health_thread_stall"
SESSIOND_PRELOAD=".libs/libhealthstall.so"
TEST_SUFFIX="STALL"
CURDIR=$(dirname $(readlink -f $0))

source ${CURDIR}/test_health.sh
