#!/bin/bash
#
# Copyright (C) - 2012 David Goulet <dgoulet@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
TEST_DESC="UST tracer - Start tracing before and after execution"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../..
NR_ITER=100
NR_USEC_WAIT=100000
TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME/$TESTAPP_NAME"
SESSION_NAME="per-session"
EVENT_NAME="tp:tptest"
NUM_TESTS=16

source $TESTDIR/utils/utils.sh

if [ ! -x "$TESTAPP_BIN" ]; then
	BAIL_OUT "No UST nevents binary detected."
fi

# MUST set TESTDIR before calling those functions

function test_before_apps()
{
	# BEFORE application is spawned
	create_lttng_session_ok $SESSION_NAME $TRACE_PATH
	enable_ust_lttng_event_ok $SESSION_NAME $EVENT_NAME
	start_lttng_tracing_ok $SESSION_NAME

	$TESTAPP_BIN $NR_ITER $NR_USEC_WAIT &
	wait
	ok $? "Traced application stopped."

	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME

	trace_match_only $EVENT_NAME $NR_ITER $TRACE_PATH

	return $?
}

function test_after_apps()
{
	local out
	local file_sync_after_first=$(mktemp -u)
	local file_sync_before_last=$(mktemp -u)

	create_lttng_session_ok $SESSION_NAME $TRACE_PATH
	enable_ust_lttng_event_ok $SESSION_NAME $EVENT_NAME

	$TESTAPP_BIN $NR_ITER $NR_USEC_WAIT ${file_sync_after_first} ${file_sync_before_last} &
	ok $? "Application started in background."

	start_lttng_tracing_ok $SESSION_NAME

	touch ${file_sync_before_last}

	wait

	stop_lttng_tracing_ok $SESSION_NAME
	destroy_lttng_session_ok $SESSION_NAME

	rm -f ${file_sync_after_first}
	rm -f ${file_sync_before_last}

	validate_trace $EVENT_NAME $TRACE_PATH
	out=$?

	return $out
}

# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

start_lttng_sessiond

diag "Start tracing BEFORE application is started"

TRACE_PATH=$(mktemp -d)

test_before_apps
out=$?
if [ $out -ne 0 ]; then
	stop_lttng_sessiond
	exit $out
fi

rm -rf $TRACE_PATH

diag "Start tracing AFTER application is started"

TRACE_PATH=$(mktemp -d)

test_after_apps
out=$?
if [ $out -ne 0 ]; then
	stop_lttng_sessiond
	exit $out
fi

stop_lttng_sessiond

rm -rf $TRACE_PATH
