#!/bin/bash
#
# Copyright (C) - 2012 David Goulet <dgoulet@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
TEST_DESC="UST tracer - Start tracing before and after execution"

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../..
NR_ITER=100
NR_USEC_WAIT=100000
TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME/$TESTAPP_NAME"
SESSION_NAME="per-session"
EVENT_NAME="tp:tptest"
NUM_TESTS=17

source $TESTDIR/utils/utils.sh

if [ ! -x "$TESTAPP_BIN" ]; then
	BAIL_OUT "No UST nevents binary detected."
fi

# MUST set TESTDIR before calling those functions

function wait_app()
{
	while [ -n "$(pidof $TESTAPP_NAME)" ]; do
		sleep 0.5
	done
	pass "Application $TESTAPP_NAME ended."
}

function test_before_apps()
{
	# BEFORE application is spawned
	create_lttng_session $SESSION_NAME $TRACE_PATH
	enable_ust_lttng_event $SESSION_NAME $EVENT_NAME
	start_lttng_tracing $SESSION_NAME

	$TESTAPP_BIN $NR_ITER $NR_USEC_WAIT
	ok $? "Traced application stopped."

	stop_lttng_tracing $SESSION_NAME
	destroy_lttng_session $SESSION_NAME

	trace_matches $EVENT_NAME $NR_ITER $TRACE_PATH

	return $?
}

function test_after_apps()
{
	local out

	$TESTAPP_BIN $NR_ITER $NR_USEC_WAIT &
	ok $? "Application started in background."

	# BEFORE application is spawned
	create_lttng_session $SESSION_NAME $TRACE_PATH
	enable_ust_lttng_event $SESSION_NAME $EVENT_NAME
	start_lttng_tracing $SESSION_NAME

	# Since the start is done after the application is started, there is a
	# bootstrap time needed between the session daemon and the UST tracer.
	# Waiting for the application to end tells us when to stop everything and
	# validate that at least one event is seen.
	wait_app

	stop_lttng_tracing $SESSION_NAME
	destroy_lttng_session $SESSION_NAME

	validate_trace $EVENT_NAME $TRACE_PATH
	out=$?

	return $out
}

# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

start_lttng_sessiond

diag "Start tracing BEFORE application is started"

TRACE_PATH=$(mktemp -d)

test_before_apps
out=$?
if [ $out -ne 0 ]; then
	stop_lttng_sessiond
	exit $out
fi

rm -rf $TRACE_PATH

diag "Start tracing AFTER application is started"

TRACE_PATH=$(mktemp -d)

test_after_apps
out=$?
if [ $out -ne 0 ]; then
	stop_lttng_sessiond
	exit $out
fi

stop_lttng_sessiond

rm -rf $TRACE_PATH
