#!/bin/bash
#
# Copyright (C) - 2020 EfficiOS, inc
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

# Test the `lttng list-trigger` command line interface.

CURDIR="$(dirname "$0")"
TESTDIR="$CURDIR/../../.."

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"


NUM_TESTS=82

FULL_LTTNG_BIN="${TESTDIR}/../src/bin/lttng/${LTTNG_BIN}"

tmp_stdout=$(mktemp -t test_list_triggers_cli_stdout.XXXXXX)
tmp_stderr=$(mktemp -t test_list_triggers_cli_stderr.XXXXXX)
tmp_expected_stdout=$(mktemp -t test_list_triggers_cli_expected_stdout.XXXXXX)
uprobe_elf_binary=$(realpath "${TESTDIR}/utils/testapp/userspace-probe-elf-binary/.libs/userspace-probe-elf-binary")
uprobe_sdt_binary=$(realpath "${TESTDIR}/utils/testapp/userspace-probe-sdt-binary/.libs/userspace-probe-sdt-binary")

uid=$(id --user)
gid=$(id --group)

if [ "$uid" == "0" ]; then
	ist_root=1
	ls "$uprobe_sdt_binary" >/dev/null 2>&1
	if test $? == 0; then
		hast_sdt_binary=1
	else
		hast_sdt_binary=0
	fi
else
	ist_root=0
	hast_sdt_binary=0
fi


function list_triggers_matches_ok ()
{
	local test_name="$1"
	local expected_stdout_file="$2"

	"${FULL_LTTNG_BIN}" list-triggers > "${tmp_stdout}" 2> "${tmp_stderr}"
	ok $? "${test_name}: exit code is 0"

	diff -u "${expected_stdout_file}" "${tmp_stdout}"
	ok $? "${test_name}: expected stdout"

	diff -u /dev/null "${tmp_stderr}"
	ok $? "${test_name}: expected stderr"
}

test_top_level_options ()
{
	diag "Listing top level options"

	lttng_add_trigger_ok "hello" --condition event-rule-matches -u test-id --action notify

	cat > "${tmp_expected_stdout}" <<- EOF
	- name: hello
	  user id: ${uid}
	  condition: event rule hit
	    rule: test-id (type: tracepoint, domain: ust)
	  actions:
	    notify
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "top level options" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "hello"
}

test_on_event_tracepoint ()
{
	diag "Listing on-event tracepoint"

	lttng_add_trigger_ok "C" --condition event-rule-matches -u -a --action notify
	lttng_add_trigger_ok "A" --condition event-rule-matches aaa -u --filter 'p == 2' --action notify
	lttng_add_trigger_ok "D" --condition event-rule-matches 'hello*' -u -x 'hello2,hello3,hello4' --action notify
	lttng_add_trigger_ok "B" --condition event-rule-matches -u gerboise --loglevel INFO --action notify
	lttng_add_trigger_ok "E" --condition event-rule-matches -u lemming --loglevel-only WARNING --action notify
	lttng_add_trigger_ok "F" --condition event-rule-matches -u capture-payload-field --capture a --action notify
	lttng_add_trigger_ok "G" --condition event-rule-matches -u capture-array --capture 'a[2]' --capture '$ctx.tourlou[18]' --action notify
	lttng_add_trigger_ok "H" --condition event-rule-matches -u capture-chan-ctx --capture '$ctx.vpid' --action notify
	lttng_add_trigger_ok "I" --condition event-rule-matches -u capture-app-ctx --capture '$app.iga:active_clients' --action notify

	cat > "${tmp_expected_stdout}" <<- EOF
	- name: A
	  user id: ${uid}
	  condition: event rule hit
	    rule: aaa (type: tracepoint, domain: ust, filter: p == 2)
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: B
	  user id: ${uid}
	  condition: event rule hit
	    rule: gerboise (type: tracepoint, domain: ust, log level at least INFO)
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: C
	  user id: ${uid}
	  condition: event rule hit
	    rule: * (type: tracepoint, domain: ust)
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: D
	  user id: ${uid}
	  condition: event rule hit
	    rule: hello* (type: tracepoint, domain: ust, exclusions: hello2,hello3,hello4)
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: E
	  user id: ${uid}
	  condition: event rule hit
	    rule: lemming (type: tracepoint, domain: ust, log level is WARNING)
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: F
	  user id: ${uid}
	  condition: event rule hit
	    rule: capture-payload-field (type: tracepoint, domain: ust)
	    captures:
	      - a
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: G
	  user id: ${uid}
	  condition: event rule hit
	    rule: capture-array (type: tracepoint, domain: ust)
	    captures:
	      - a[2]
	      - \$ctx.tourlou[18]
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: H
	  user id: ${uid}
	  condition: event rule hit
	    rule: capture-chan-ctx (type: tracepoint, domain: ust)
	    captures:
	      - \$ctx.vpid
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: I
	  user id: ${uid}
	  condition: event rule hit
	    rule: capture-app-ctx (type: tracepoint, domain: ust)
	    captures:
	      - \$app.iga:active_clients
	  actions:
	    notify
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "event-rule-matches, tracepoint event rule" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "A"
	lttng_remove_trigger_ok "B"
	lttng_remove_trigger_ok "C"
	lttng_remove_trigger_ok "D"
	lttng_remove_trigger_ok "E"
	lttng_remove_trigger_ok "F"
	lttng_remove_trigger_ok "G"
	lttng_remove_trigger_ok "H"
	lttng_remove_trigger_ok "I"
}

test_on_event_probe ()
{
	local channel_enable_addr
	local channel_disable_addr

	diag "Listing on-event kernel probe"

	channel_enable_addr=$(grep ' t lttng_channel_enable\s\[lttng_tracer\]$' /proc/kallsyms | cut -f 1 -d ' ')
	channel_disable_addr=$(grep ' t lttng_channel_disable\s\[lttng_tracer\]$' /proc/kallsyms | cut -f 1 -d ' ')

	# We need to find a valid offset.
	base_symbol=""
	offset=0
	if [[ 0x$channel_enable_addr -lt 0x$channel_disable_addr ]]; then
		base_symbol="lttng_channel_enable"
		offset=$(( 0x$channel_disable_addr - 0x$channel_enable_addr ))
	else
		base_symbol="lttng_channel_disable"
		offset=$(( 0x$channel_enable_addr - 0x$channel_disable_addr ))
	fi

	offset_hex="0x$(printf '%x' $offset)"

	lttng_add_trigger_ok "T0" --condition event-rule-matches -k --probe=lttng_channel_enable my_channel_enable --action notify
	lttng_add_trigger_ok "T1" --condition event-rule-matches -k --probe="${base_symbol}+${offset_hex}" my_channel_enable --action notify
	lttng_add_trigger_ok "T2" --condition event-rule-matches -k --probe="0x${channel_enable_addr}" my_channel_enable --action notify

	cat > "${tmp_expected_stdout}" <<- EOF
	- name: T0
	  user id: ${uid}
	  condition: event rule hit
	    rule: my_channel_enable (type: probe, location: lttng_channel_enable)
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: T1
	  user id: ${uid}
	  condition: event rule hit
	    rule: my_channel_enable (type: probe, location: ${base_symbol}+${offset_hex})
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: T2
	  user id: ${uid}
	  condition: event rule hit
	    rule: my_channel_enable (type: probe, location: 0x${channel_enable_addr})
	  actions:
	    notify
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "event-rule-matches, probe event rule" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "T0"
	lttng_remove_trigger_ok "T1"
	lttng_remove_trigger_ok "T2"
}

test_on_event_userspace_probe_elf ()
{
	local elf_function_name="test_function"

	diag "Listing on-event userspace-probe elf"

	lttng_add_trigger_ok "T0" --condition event-rule-matches -k --userspace-probe=${uprobe_elf_binary}:test_function ma-probe-elf --action notify

	cat > "${tmp_expected_stdout}" <<- EOF
	- name: T0
	  user id: ${uid}
	  condition: event rule hit
	    rule: ma-probe-elf (type: userspace probe, location type: ELF, location: ${uprobe_elf_binary}:${elf_function_name})
	  actions:
	    notify
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "event-rule-matches, userspace-probe event rule" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "T0"
}

test_on_event_userspace_probe_sdt ()
{
	local sdt_provider_name="foobar"
	local sdt_probe_name="tp1"

	diag "on-event userspace-probe sdt"

	lttng_add_trigger_ok "T0" --condition on-event -k --userspace-probe=sdt:${uprobe_sdt_binary}:${sdt_provider_name}:${sdt_probe_name} ma-probe-sdt --action notify

	cat > "${tmp_expected_stdout}" <<- EOF
	- id: T0
	  user id: 0
	  condition: event rule hit
	    rule: ma-probe-sdt (type: userspace probe, location type: SDT, location: ${uprobe_sdt_binary}:${sdt_provider_name}:${sdt_probe_name})
	  actions:
	    notify
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "on-event, userspace-probe event rule SDT" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "T0"
}

test_on_event_syscall ()
{
	diag "Listing on-event syscall"

	lttng_add_trigger_ok "T0" --condition event-rule-matches -k --syscall open --action notify
	lttng_add_trigger_ok "T1" --condition event-rule-matches -k --syscall ptrace --filter 'a > 2' --action notify

	cat > "${tmp_expected_stdout}" <<- EOF
	- name: T0
	  user id: ${uid}
	  condition: event rule hit
	    rule: open (type: syscall)
	  actions:
	    notify
	      errors: none
	  errors: none
	- name: T1
	  user id: ${uid}
	  condition: event rule hit
	    rule: ptrace (type: syscall, filter: a > 2)
	  actions:
	    notify
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "event-rule-matches, syscall event rule" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "T0"
	lttng_remove_trigger_ok "T1"
}

test_snapshot_action ()
{
	diag "Listing snapshot actions"

	lttng_add_trigger_ok "T0" --condition event-rule-matches -u some-event --action snapshot-session ze-session
	lttng_add_trigger_ok "T1" --condition event-rule-matches -u some-event --action snapshot-session ze-session --path /some/path
	lttng_add_trigger_ok "T2" --condition event-rule-matches -u some-event --action snapshot-session ze-session --url file:///some/other/path
	lttng_add_trigger_ok "T3" --condition event-rule-matches -u some-event --action snapshot-session ze-session --url net://1.2.3.4
	lttng_add_trigger_ok "T4" --condition event-rule-matches -u some-event --action snapshot-session ze-session --url net://1.2.3.4:1234:1235
	lttng_add_trigger_ok "T5" --condition event-rule-matches -u some-event --action snapshot-session ze-session --ctrl-url=tcp://1.2.3.4:1111 --data-url=tcp://1.2.3.4:1112
	lttng_add_trigger_ok "T6" --condition event-rule-matches -u some-event --action snapshot-session ze-session --path /some/path --max-size=1234
	lttng_add_trigger_ok "T7" --condition event-rule-matches -u some-event --action snapshot-session ze-session --path /some/path --name=meh
	lttng_add_trigger_ok "T8" --condition event-rule-matches -u some-event --action snapshot-session ze-session --rate-policy=every:10
	lttng_add_trigger_ok "T9" --condition event-rule-matches -u some-event --action snapshot-session ze-session --rate-policy=once-after:10

	cat > "${tmp_expected_stdout}" <<- EOF
	- name: T0
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`
	      errors: none
	  errors: none
	- name: T1
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, path: /some/path
	      errors: none
	  errors: none
	- name: T2
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, path: /some/other/path
	      errors: none
	  errors: none
	- name: T3
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, url: net://1.2.3.4
	      errors: none
	  errors: none
	- name: T4
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, url: net://1.2.3.4:1234:1235
	      errors: none
	  errors: none
	- name: T5
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, control url: tcp://1.2.3.4:1111, data url: tcp://1.2.3.4:1112
	      errors: none
	  errors: none
	- name: T6
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, path: /some/path, max size: 1234
	      errors: none
	  errors: none
	- name: T7
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, path: /some/path, name: meh
	      errors: none
	  errors: none
	- name: T8
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, rate policy: after every 10 occurrences
	      errors: none
	  errors: none
	- name: T9
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    snapshot session \`ze-session\`, rate policy: once after 10 occurrences
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "snapshot action" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "T0"
	lttng_remove_trigger_ok "T1"
	lttng_remove_trigger_ok "T2"
	lttng_remove_trigger_ok "T3"
	lttng_remove_trigger_ok "T4"
	lttng_remove_trigger_ok "T5"
	lttng_remove_trigger_ok "T6"
	lttng_remove_trigger_ok "T7"
	lttng_remove_trigger_ok "T8"
	lttng_remove_trigger_ok "T9"
}

test_notify_action ()
{
	lttng_add_trigger_ok "T0" --condition event-rule-matches -u some-event --action notify --rate-policy=once-after:5
	lttng_add_trigger_ok "T1" --condition event-rule-matches -u some-event --action notify --rate-policy=every:10

	cat > "${tmp_expected_stdout}" <<- EOF
	- name: T0
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    notify, rate policy: once after 5 occurrences
	      errors: none
	  errors: none
	- name: T1
	  user id: ${uid}
	  condition: event rule hit
	    rule: some-event (type: tracepoint, domain: ust)
	  actions:
	    notify, rate policy: after every 10 occurrences
	      errors: none
	  errors: none
	EOF

	list_triggers_matches_ok "snapshot action" "${tmp_expected_stdout}"

	lttng_remove_trigger_ok "T0"
	lttng_remove_trigger_ok "T1"
}

plan_tests $NUM_TESTS

# shellcheck disable=SC2119
start_lttng_sessiond_notap

test_top_level_options
test_on_event_tracepoint
skip $ist_root "non-root user: skipping kprobe tests" 9 || test_on_event_probe
skip $ist_root "non-root user: skipping userspace probe elf tests" 5 || test_on_event_userspace_probe_elf
skip $(($ist_root && $hast_sdt_binary)) "skipping userspace probe SDT tests" 5 || test_on_event_userspace_probe_sdt
skip $ist_root "non-root user: skipping syscall tests" 7 || test_on_event_syscall
test_snapshot_action
test_notify_action

stop_lttng_sessiond_notap

# Cleanup
rm -f "${tmp_stdout}"
rm -f "${tmp_stderr}"
rm -f "${tmp_expected_stdout}"
