#!/bin/bash
#
# SPDX-FileCopyrightText: 2015 Jonathan Rajotte <jonathan.rajotte-julien@efficios.com>
# SPDX-FileCopyrightText: 2016 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
# SPDX-FileCopyrightText: 2025 Michael Jeanson <mjeanson@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

TEST_DESC="UST - Rotation destroy flush"

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../..

TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME"

NUM_EVENT=1000000
EVENT_NAME="tp:tptest"

TEST_RUNS=10
NUM_TESTS=$((19 * TEST_RUNS))

# shellcheck source-path=SCRIPTDIR/../../..
source "$TESTDIR/utils/utils.sh"

# Ensure the daemons invoke abort on error.
check_skip_kernel_test || export LTTNG_ABORT_ON_ERROR=1

# MUST set TESTDIR before calling those functions

function test_rotation_destroy_flush_single()
{
	local session_name="rotation_destroy_flush"
	local channel_name="page_size_chan"
	local trace_path
	local file_testapp_output

	trace_path=$(mktemp -d -t "tmp.${FUNCNAME[0]}_trace_path.XXXXXX")
	file_testapp_output=$(mktemp -u -t "tmp.${FUNCNAME[0]}_testapp_output.XXXXXX")

	start_lttng_sessiond

	create_lttng_session_ok $session_name "$trace_path"
	enable_ust_lttng_channel_ok $session_name $channel_name --buffer-ownership=process --tracefile-size="$(getconf PAGE_SIZE)"
	enable_ust_lttng_event_ok $session_name $EVENT_NAME $channel_name
	start_lttng_tracing_ok $session_name

	run_testapp_ok "$file_testapp_output" "$TESTAPP_BIN" -i $NUM_EVENT

	# stop and destroy
	stop_lttng_tracing_ok $session_name
	destroy_lttng_session_ok $session_name

	validate_trace_count_range_incl_min_excl_max "$EVENT_NAME" "${trace_path}" 1 $NUM_EVENT

	rm -rf "$trace_path"
	trace_path=$(mktemp -d -t "tmp.${FUNCNAME[0]}_trace_path.XXXXXX")

	create_lttng_session_ok $session_name "$trace_path"
	enable_ust_lttng_channel_ok $session_name $channel_name --buffer-ownership=process --tracefile-size="$(getconf PAGE_SIZE)"
	enable_ust_lttng_event_ok $session_name $EVENT_NAME $channel_name
	start_lttng_tracing_ok $session_name

	run_testapp_ok "$file_testapp_output" "$TESTAPP_BIN" -i $NUM_EVENT

	# destroy only
	destroy_lttng_session_ok $session_name
	stop_lttng_sessiond

	validate_trace_count_range_incl_min_excl_max "$EVENT_NAME" "${trace_path}" 1 $NUM_EVENT

	rm -rf "$trace_path"
	rm -f "$file_testapp_output"
}

function test_rotation_destroy_flush()
{
	for a in $(seq 1 ${TEST_RUNS}); do
		diag "Test run ${a}/${TEST_RUNS}"
		test_rotation_destroy_flush_single
	done
}

plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

test_rotation_destroy_flush
