#!/bin/bash
#
# SPDX-FileCopyrightText: 2021 Francis Deslauriers <francis.deslauriers@efficios.com>
#
# SPDX-License-Identifier: GPL-2.0-only

TEST_DESC="LTTng - Channel tests"

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../..

TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME"

NR_ITER=100
NR_USEC_WAIT=1

NUM_TESTS=16

# shellcheck source-path=SCRIPTDIR/../../..
source "$TESTDIR/utils/utils.sh"

function test_channel_disable_stopped_session()
{
	local session_name="test_channel"
	local chan_name="channel0"
	local event_name="tp:tptest"

	local trace_path
	local file_testapp_output

	trace_path=$(mktemp -d -t "tmp.${FUNCNAME[0]}_trace_path.XXXXXX")
	file_testapp_output=$(mktemp -u -t "tmp.${FUNCNAME[0]}_testapp_output.XXXXXX")

	diag "Test channel disable on stop session"

	create_lttng_session_ok "$session_name" "$trace_path"

	enable_ust_lttng_channel_ok "$session_name" "$chan_name"

	enable_ust_lttng_event_ok "$session_name" "$event_name" "$chan_name"

	start_lttng_tracing_ok "$session_name"

	run_testapp_ok "$file_testapp_output" "$TESTAPP_BIN" -i "$NR_ITER" -w "$NR_USEC_WAIT"

	stop_lttng_tracing_ok "$session_name"

	trace_match_only "$event_name" "$NR_ITER" "$trace_path"

	lttng_clear_session_ok "$session_name"

	disable_ust_lttng_channel "$session_name" "$chan_name"

	start_lttng_tracing_ok "$session_name"

	# The channel is disabled so no events should be emited by this app.
	run_testapp_ok "$file_testapp_output" "$TESTAPP_BIN" -i "$NR_ITER" -w "$NR_USEC_WAIT"

	stop_lttng_tracing_ok "$session_name"

	trace_match_only "$event_name" 0 "$trace_path"

	destroy_lttng_session_ok "$session_name"

	rm -rf "$trace_path"
	rm -f "$file_testapp_output"
}


# MUST set TESTDIR before calling those functions
plan_tests $NUM_TESTS

print_test_banner "$TEST_DESC"

bail_out_if_no_babeltrace

start_lttng_sessiond

if [ ! -x "$TESTAPP_BIN" ]; then
	BAIL_OUT "No UST nevents binary detected."
fi

test_channel_disable_stopped_session

stop_lttng_sessiond
